### ISSUE TITLE
Rename Hakai ERDDAP repository?

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-erddap#170]
The present repository isn't quite self explanatory about the purpose of the repo and should mention ERDDAP in it. 

We should perhaps rename this repo `hakai-erddap` which is following the convention used by the other similar repositories maintained by CIOOS:
- cioos-pacific-erddap
- cioos-atlantic-erddap

## Issue
Renaming this repo may have some consequences on other external infrastructure. It would be good to identify them first prior to make the changes.

@n-a-t-e @fostermh @raytula @steviewanders  any thoughts?

**Comment by n-a-t-e** [comment]
https://github.com/hakaiInstitute/hakai-erddap will need to be deleted first, if its no longer used

**Comment by JessyBarrette** [comment]
> How to test the consequences?
Not too sure as far as I know we did share with some external groups the repo just to show them how we're structuring the related erddap files. Anything else is more pointing to the actual deployment and not the related repo. 

deleting present `hakai-erddap` . Yes I can we can rename that one with a prefix `historical` and then archive it. Not sure if there's a prefered term to use for such cases.

**Comment by n-a-t-e** [comment]
As for moving/renaming, we've done a fair bit of this and it has worked well. Eg https://github.com/hakaiInstitute/ios-erddap and https://github.com/HakaiInstitute/salish-sea-viewer

**Comment by JessyBarrette** [comment]
oups I just realized that I don't have any admin access to the repo 
<https://github.com/HakaiInstitute/hakai-erddap> to archive this repo and replace the present one name by `hakai-erddap`

@n-a-t-e would you mind sharing admin to it?

**Comment by JessyBarrette** [comment]
@steviewanders can you rename that repo https://github.com/HakaiInstitute/hakai-erddap  so we can replace that one by `hakai-erddap`

**Comment by JessyBarrette** [comment]
Sweet thanks
