### ISSUE TITLE
hakai server catalogue.hakai.org docker v1.40

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-erddap#180]
Hakai server catalogue.hakai.org is using an old docker version which isn't compatible with the latest erddap version 2.23.

It would be good to upgrade it. 

A few other services are running on this machine, which I think are related to CKAN.

@fostermh any problems with upgrading docker. I guess we'll have to stop the catalogue to upgrade.

related to https://gitkraken.dev/link/Z2l0a3Jha2VuOi8vcmVwb2xpbmsvNTMxZjE0ZTVlZWMwZDQxZmZiZDRlZDkwYmNmMGE4NmQzYWRjMjMyMy9icmFuY2gvbWFzdGVyP3VybD1odHRwcyUzQSUyRiUyRmdpdGh1Yi5jb20lMkZIYWthaUluc3RpdHV0ZSUyRmhha2FpLWRhdGFzZXRzLmdpdA%3D%3D?origin=gitkraken

**Comment by fostermh** [comment]
upgrade is fine but I won't be able to help until I'm back from vacation on June 8th.

**Comment by JessyBarrette** [comment]
ok no rush I downgraded the ERDDAP version for now, it will be fine until you're back since I don't really how CKAN is working :). Have a great time off!
