### ISSUE TITLE
ERDDAP notifications - Update notifications account password with new OAuth

### ISSUE THREAD

**Issue by radarsymphony** [HakaiInstitute/hakai-erddap#201]
This change might involve swapping in a new plain text password once it has been created.

I think it would be the corresponding location in production of this sample .env file: https://github.com/HakaiInstitute/hakai-erddap/blob/master/sample.env

**Comment by radarsymphony** [comment]
Hi @fostermh I'm just checking in. Will you close this issue if/when you've made the changes on your end?

**Comment by fostermh** [comment]
done. updated /home/hakai/hakai-erddap/.env on catalogue.hakai.org to the new app password
