### ISSUE TITLE
[Issue]: HakaiKCBuoy1hour - KCBuoy ERDDAP dataset no longer working

### ISSUE THREAD

**Issue by raytula** [HakaiInstitute/hakai-erddap#207]
### Level

High

### Issue Description

Wiley wrote to Ray: "On a different note, do you know why the KC buoy isn't showing up on the NANOOS NVS? https://nvs.nanoos.org/Explorer"

The [dataset itself is still online](https://catalogue.hakai.org/erddap/tabledap/HakaiKCBuoy1hour.html)

However, the following error is presented when attempting to access the data:

```
Error {
    code=500;
    message="Internal Server Error: ERROR from data source: org.postgresql.util.PSQLException: ERROR: column \"KCBuoy:WaterTemp_Std\" does not exist
  Hint: Perhaps you meant to reference the column \"HakaiKCBuoy1hour.KCBuoy:WaterTemp_Med\".
  Position: 736";
}
```

so, looks like an underlying table or view definition may have changed.

### Issue Solution

Looking into the cause of the SQL error and either adjusting the underling schema to match the query or updating the query to match the underlying data.

**Comment by fostermh** [comment]
it looks like https://github.com/HakaiInstitute/hakai-erddap/pull/182 removed the watertemp_std column from the database view but did not update the corresponding dataset.xml file for this dataset in erddap. thus erddap is looking for the column but can't find it. I will update erddap now.

**Comment by fostermh** [comment]
data is once again live on nanoose
https://nvs.nanoos.org/Explorer?action=oiw:fixed_platform:HAKAI_KCBuoy:observations:A1_AirTemp

**Comment by raytula** [comment]
> data is once again live on nanoose
> https://nvs.nanoos.org/Explorer?action=oiw:fixed_platform:HAKAI_KCBuoy:observations:A1_AirTemp

Thanks@fostermh
